site_name: Conduit Docs
site_description: Conduit is a simple, fast and reliable chat server for the Matrix protocol
theme:
  name: material
repo_url: https://gitlab.com/famedly/conduit
nav:
  - Home: index.md
  - Installation:
      - Prerequisites: installation/prerequisites.md
      - Distribution Packages: installation/packages.md
      - Manual: installation/manual.md
      - Docker: installation/docker.md
  - Configuration:
      - Conduit.toml: configuration/conduit.toml.md
      - Appservices: configuration/appservices.md
  - Development:
      - Basics: development/basics.md
      - Cross compilation: development/cross-compilation.md
      - Tests & CI: development/tests-ci.md

